yatube/posts/urls.py
# posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
	path('group/<slug:slug>/', views.group_posts, name = 'group_list'),
    path('', views.index, name = 'main'),
] 

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('', include('posts.urls', namespace = 'posts')),
    path('admin/', admin.site.urls)
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Group(models.Model):
    title = models.CharField(max_length = 300)
    slug = 	models.CharField(max_length = 30)
    description = models.TextField()
    def __str__(self):
        return self.title
		

class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField()
    author = models.ForeignKey(
    User,
    on_delete = models.CASCADE,
    related_name = 'posts'
	)
    group = models.ForeignKey(
	Group,
    blank = True, null = True,
    on_delete = models.CASCADE
	)
	
	
# Create your models here.

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Post, Group

# Create your views here.
def index(request):
    template = 'posts/index.html'
    posts = Post.objects.order_by('-pub_date')[:10]
    context = {
        'posts': posts,
    }
    return render(request, template, context)
	
	
def group_posts(request, slug):
    template = 'posts/group_posts.html'
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'group': group,
        'posts': posts,
		'titleGroup': group.title
    }
    return render(request, template, context) 	

yatube/templates/includes/base.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>    
    {%include 'includes/head.html'%}
	{%block title%}
	<title>Тут у нас блочок с заголовком</title>
	{%endblock%}
  </head>
  <body>
    <header>
      {%include 'includes/header.html'%}
    </header>
    <main> 
	{% block content %}
        Контент не подвезли :(
    {% endblock %} 
    </main>
    <!-- Использованы классы бустрапа: -->
    <!-- border-top: создаёт тонкую линию сверху блока -->
    <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
    <!-- py-3: контент внутри размещается с отступом сверху и снизу -->         
    <footer class="border-top text-center py-3">
      {%include 'includes/footer.html'%}
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
      <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
      <p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>   

yatube/templates/includes/group_list.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
{%extends 'includes/base.html'%}
{%block content%}
<!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
        <h1>Лев Толстой – зеркало русской революции.</h1>
        <p>
          Группа тайных поклонников графа.
        </p>
        <article>
          <ul>
            <li>
              Автор: Лев Толстой
            </li>
            <li>
              Дата публикации: 30 июля 1854
            </li>
          </ul>      
          <p>
            [Рымник.] Сдѣлалъ верхомъ переходъ до Рымника. [[5]] Старикъ все не кланяется мнѣ.
            Обѣ вещи эти злятъ меня. Съ встрѣчавшимися баши-бузуками велъ себя хорошо. 
            Объяснился съ Крыжановскимъ. Онъ, не знаю зачѣмъ, совѣтуетъ мнѣ прикомандироваться 
            къ казачьей батареѣ; совѣтъ, которому я не послѣдую. Желчно спорилъ вечеромъ съ Фриде 
            и Бабарыкинымъ, ругалъ Сержпутовскому и ничего не сдѣлалъ, вотъ 3 упрека, которыя дѣлаю с
            ебѣ за нынѣшній день. (3)
          </p>         
        </article>
        <hr>
        <article>
          <ul>
            <li>
              Автор: Лев Толстой
            </li>
            <li>
              Дата публикации: 29 июля 1854
            </li>
          </ul> 
          <p>
            Исправленіе мое идетъ прекрасно. Я чувствую, какъ отношенія мои становятся пріятны и легки 
            съ людьми всякаго рода, съ тѣхъ поръ какъ я рѣшился быть скромнымъ и убѣдился въ томъ, 
            что казаться всегда величественнымъ и непогрѣшнымъ вовсе не есть необходимость. Я очень 
            веселъ. И дай Богъ, какъ мнѣ кажется, — чтобы веселье это происходило отъ самаго меня; 
            отъ желаній всѣмъ быть пріятнымъ, скромности, необидчивости и внимательности за вспышками. 
            — Тогда бы я всегда былъ веселъ и почти всегда счастливъ. 
            Утромъ рѣшилъ было сидѣть дома, позаниматься, но дѣло не пошло и не утерпѣлъ вечеромъ, 
            чтобы не пойдти пошляться. Идя отъ ужина, мы съ Тишк[евичемъ] остановились у бардели и насъ 
            накрылъ Крыжановскій, что, признаюсь, было мнѣ не совсѣмъ пріятно. Упрекаю себя за 
            безхарактерность, что не высидѣлъ дома, и зa праздность цѣлаго дня. Это главный пунктъ. (2)
          </p>      
        </article>
        <hr>
        <article>
          <ul>
            <li>
              Автор: Лев Толстой
            </li>
            <li>
              Дата публикации: 28 июля 1854
            </li>
          </ul> 
          <p>
            Пишу въ самомъ пріятномъ веселомъ расположеніи духа, въ которомъ я провелъ весь вечеръ. 
            Утро читалъ, объѣдался грушами и вмѣсто обѣда ѣлъ сыръ. Несмотря на кутежи у Сталыпина и 
            Сержпутовскаго по случаю полученія наградъ, не завидовалъ, а провелъ день весело. Вечеромъ 
            хватилъ босонож[ку] и выпилъ бокала два шампанскаго съ Шварц[емъ], Вейлеровскимъ [?] и 
            Гембичомъ, потомъ болталъ съ Шубинымъ и съ Сашей Горчаковымъ. — Исключая праздности, 
            днемъ своимъ очень доволенъ. (1)
          </p>
        </article>
        <!-- под последним постом нет линии -->
      </div>  
{%endblock%}

yatube/templates/includes/head.html
    {% load static %}
	<meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="{%static 'img/logo.png'%}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{%static 'img/fav/apple-touch-icon.png'%}">
    <link rel="icon" type="image/png" sizes="32x32" href="{%static 'img/fav/favicon-32x32.png'%}">
    <link rel="icon" type="image/png" sizes="16x16" href="{%static 'img/fav/favicon-16x16.png'%}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">

yatube/templates/includes/header.html
 <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
      <!-- В дальнейшем тут будет создано полноценное меню -->
	  {% load static %}
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="{%url 'posts:main'%}">
            <img src="{%static 'img/logo.png'%}" width="30" height="30" class="d-inline-block align-top" alt="">
            <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
            <span style="color:red">Ya</span>tube
          </a>
        </div>
      </nav>     

yatube/templates/includes/index.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  {%extends 'includes/base.html'%}
  {%block title%}
  <title>Последние обновления на сайте</title>
  {%endblock%}
  {%block content%}
   {% for post in posts %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text }}</p>    
  <a href="">все записи группы</a>
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %} 
  {% endblock %}

yatube/templates/posts/group_posts.html
<!-- templates/posts/index.html -->
<!DOCTYPE html> 
{%extends 'includes/base.html'%}
  {%block title%}
    <title>Группы</title>
  {%endblock%}
   {%block content%}
<p>
          {{titleGroup}}
        </p>
   {% for post in posts %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text }}</p>
  {%endfor%}
   {% endblock %}

yatube/templates/posts/index.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  {%extends 'includes/base.html'%}
  {%block title%}
  <title>Последние обновления на сайте</title>
  {%endblock%}
  {%block content%}
   {% for post in posts %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text }}</p>    
  {% if post.group %}   
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% else %}
	<a>единственная запись в группе</a>
  {% endif %} 
  {% if not forloop.last %}<hr>{% endif %}
 {% endfor %}   
  {% endblock %}